name: 'Skyhook Login to AWS'
description: 'Authenticate to AWS using OIDC with optional ECR login and EKS setup'
author: 'Skyhook'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  aws_region:
    description: 'AWS region'
    required: true
  
  role_to_assume:
    description: 'ARN of the IAM role to assume (for OIDC)'
    required: false
  
  role_session_name:
    description: 'Name for the assumed role session'
    required: false
    default: 'github-actions-${{ github.run_id }}'
  
  role_duration:
    description: 'Duration of the role session in seconds'
    required: false
    default: '3600'

  aws_access_key_id:
    description: 'AWS Access Key ID (if not using OIDC)'
    required: false

  aws_secret_access_key:
    description: 'AWS Secret Access Key (if not using OIDC)'
    required: false

  enable_ecr_login:
    description: 'Enable Docker login to Amazon ECR'
    required: false
    default: 'false'
  
  eks_cluster_name:
    description: 'Name of the EKS cluster to configure kubectl for'
    required: false
  
  ecr_registries:
    description: 'Comma-separated list of ECR registry IDs for cross-account access'
    required: false
  
  ecr_repositories:
    description: 'Comma-separated list of ECR repositories to ensure exist (e.g., "backend,frontend")'
    required: false
    default: ''

  codeartifact_domain:
    description: 'CodeArtifact domain name'
    required: false

  codeartifact_repository:
    description: 'CodeArtifact repository name'
    required: false

  codeartifact_tool:
    description: 'Tool to configure for CodeArtifact (npm, pip, twine, dotnet, nuget, swift, maven, gradle)'
    required: false

  codeartifact_region:
    description: 'Region for CodeArtifact (defaults to aws_region if not specified)'
    required: false

  codeartifact_domain_owner:
    description: 'AWS account ID that owns the CodeArtifact domain (defaults to authenticated account)'
    required: false

  codeartifact_duration:
    description: 'Duration of the CodeArtifact token in seconds'
    required: false
    default: '43200'

  codeartifact_namespace:
    description: 'CodeArtifact namespace for the repository'
    required: false

  codeartifact_output_token:
    description: 'Output the CodeArtifact token instead of using aws codeartifact login (useful for custom configurations)'
    required: false
    default: 'false'

outputs:
  aws_account_id:
    description: 'AWS Account ID'
    value: ${{ steps.aws.outputs.aws-account-id }}

  ecr_registry:
    description: 'ECR registry URL'
    value: ${{ steps.login-ecr.outputs.registry }}

  ecr_logged_in:
    description: 'Whether ECR login was successful'
    value: ${{ steps.ecr-status.outputs.logged_in }}

  kubectl_context:
    description: 'Kubernetes context name if EKS was configured'
    value: ${{ steps.eks.outputs.context }}

  codeartifact_logged_in:
    description: 'Whether CodeArtifact login was successful'
    value: ${{ steps.codeartifact-status.outputs.logged_in }}

  codeartifact_endpoint:
    description: 'CodeArtifact repository endpoint URL (set when using token mode or Maven/Gradle)'
    value: ${{ steps.codeartifact-token.outputs.endpoint }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        role-session-name: ${{ inputs.role_session_name }}
        role-duration-seconds: ${{ inputs.role_duration }}
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
        mask-aws-account-id: false

    - name: Verify AWS connection
      shell: bash
      run: |
        echo "::group::AWS Authentication Status"
        aws sts get-caller-identity --output table
        echo "✅ AWS authentication successful"
        echo "::endgroup::"

    - name: Login to Amazon ECR
      id: login-ecr
      if: inputs.enable_ecr_login == 'true'
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ inputs.ecr_registries }}
        mask-password: true

    - name: Log ECR status
      id: ecr-status
      if: inputs.enable_ecr_login == 'true'
      shell: bash
      run: |
        echo "::notice::📦 ECR login successful for registry: ${{ steps.login-ecr.outputs.registry }}"
        echo "logged_in=true" >> $GITHUB_OUTPUT

    - name: Set ECR not logged in
      id: ecr-status-false
      if: inputs.enable_ecr_login != 'true'
      shell: bash
      run: |
        echo "logged_in=false" >> $GITHUB_OUTPUT
    
    - name: Ensure ECR repositories exist
      if: inputs.enable_ecr_login == 'true' && inputs.ecr_repositories != ''
      uses: skyhook-io/ensure-ecr-repository@v1
      with:
        repository-name: ${{ inputs.ecr_repositories }}
        aws-region: ${{ inputs.aws_region }}

    - name: Setup kubectl for EKS
      id: eks
      if: inputs.eks_cluster_name != ''
      shell: bash
      run: |
        echo "::group::EKS Configuration"
        
        # Update kubeconfig
        aws eks update-kubeconfig \
          --region ${{ inputs.aws_region }} \
          --name ${{ inputs.eks_cluster_name }} \
          --alias ${{ inputs.eks_cluster_name }}
        
        # Get the context name
        CONTEXT=$(kubectl config current-context)
        echo "context=$CONTEXT" >> $GITHUB_OUTPUT
        
        # Verify connection
        echo "Testing EKS connection..."
        kubectl get nodes --show-labels=false --no-headers | head -5 || true
        
        echo "✅ EKS cluster configured: ${{ inputs.eks_cluster_name }}"
        echo "📍 Context: $CONTEXT"
        echo "::endgroup::"

    - name: Validate CodeArtifact tool
      if: inputs.codeartifact_domain != '' && inputs.codeartifact_repository != '' && inputs.codeartifact_tool != ''
      shell: bash
      run: |
        case "${{ inputs.codeartifact_tool }}" in
          npm|pip|twine|dotnet|nuget|swift|maven|gradle)
            # Valid tool
            ;;
          *)
            echo "::error::Unsupported codeartifact_tool: '${{ inputs.codeartifact_tool }}'. Supported tools: npm, pip, twine, dotnet, nuget, swift, maven, gradle"
            exit 1
            ;;
        esac

    - name: Login to AWS CodeArtifact (npm, pip, twine, etc.)
      id: codeartifact
      if: inputs.codeartifact_domain != '' && inputs.codeartifact_repository != '' && inputs.codeartifact_tool != '' && inputs.codeartifact_tool != 'maven' && inputs.codeartifact_tool != 'gradle' && inputs.codeartifact_output_token != 'true'
      shell: bash
      run: |
        echo "::group::CodeArtifact Configuration"

        # Set defaults
        CA_REGION="${{ inputs.codeartifact_region }}"
        if [[ -z "$CA_REGION" ]]; then
          CA_REGION="${{ inputs.aws_region }}"
        fi

        CA_DOMAIN_OWNER="${{ inputs.codeartifact_domain_owner }}"
        if [[ -z "$CA_DOMAIN_OWNER" ]]; then
          CA_DOMAIN_OWNER="${{ steps.aws.outputs.aws-account-id }}"
        fi

        # Login to CodeArtifact
        aws codeartifact login \
          --tool "${{ inputs.codeartifact_tool }}" \
          --domain "${{ inputs.codeartifact_domain }}" \
          --domain-owner "$CA_DOMAIN_OWNER" \
          --repository "${{ inputs.codeartifact_repository }}" \
          --region "$CA_REGION" \
          --duration-seconds "${{ inputs.codeartifact_duration }}" \
          ${{ inputs.codeartifact_namespace != '' && format('--namespace {0}', inputs.codeartifact_namespace) || '' }}

        echo "✅ CodeArtifact login successful"
        echo "📦 Domain: ${{ inputs.codeartifact_domain }}"
        echo "📦 Repository: ${{ inputs.codeartifact_repository }}"
        echo "🔧 Tool: ${{ inputs.codeartifact_tool }}"
        if [[ -n "${{ inputs.codeartifact_namespace }}" ]]; then
          echo "🏷️  Namespace: ${{ inputs.codeartifact_namespace }}"
        fi
        echo "::endgroup::"

    - name: Setup AWS CodeArtifact Token Mode
      id: codeartifact-token
      if: inputs.codeartifact_domain != '' && inputs.codeartifact_repository != '' && inputs.codeartifact_tool != '' && (inputs.codeartifact_output_token == 'true' || inputs.codeartifact_tool == 'maven' || inputs.codeartifact_tool == 'gradle')
      shell: bash
      run: |
        echo "::group::CodeArtifact Token Configuration for ${{ inputs.codeartifact_tool }}"

        # Set defaults
        CA_REGION="${{ inputs.codeartifact_region }}"
        if [[ -z "$CA_REGION" ]]; then
          CA_REGION="${{ inputs.aws_region }}"
        fi

        CA_DOMAIN_OWNER="${{ inputs.codeartifact_domain_owner }}"
        if [[ -z "$CA_DOMAIN_OWNER" ]]; then
          CA_DOMAIN_OWNER="${{ steps.aws.outputs.aws-account-id }}"
        fi

        # Validate inputs
        if [[ -z "${{ inputs.codeartifact_domain }}" ]]; then
          echo "::error::codeartifact_domain is required for token mode"
          exit 1
        fi
        if [[ -z "${{ inputs.codeartifact_repository }}" ]]; then
          echo "::error::codeartifact_repository is required for token mode"
          exit 1
        fi
        if [[ -z "${{ inputs.codeartifact_tool }}" ]]; then
          echo "::error::codeartifact_tool is required for token mode"
          exit 1
        fi

        # Validate token duration (CodeArtifact max is 43200 seconds / 12 hours)
        DURATION="${{ inputs.codeartifact_duration }}"
        if ! [[ "$DURATION" =~ ^[0-9]+$ ]] || (( DURATION < 1 || DURATION > 43200 )); then
          echo "::error::codeartifact_duration must be between 1 and 43200 seconds (12 hours), got: $DURATION"
          exit 1
        fi

        # Verify AWS authentication
        if ! aws sts get-caller-identity >/dev/null 2>&1; then
          echo "::error::Not authenticated to AWS. Ensure AWS credentials are configured before CodeArtifact setup."
          exit 1
        fi

        # Determine format based on tool
        case "${{ inputs.codeartifact_tool }}" in
          npm)
            FORMAT="npm"
            ;;
          pip|twine)
            FORMAT="pypi"
            ;;
          dotnet|nuget)
            FORMAT="nuget"
            ;;
          swift)
            FORMAT="swift"
            ;;
          maven|gradle)
            FORMAT="maven"
            ;;
          *)
            echo "::error::Unknown codeartifact_tool '${{ inputs.codeartifact_tool }}'. Supported: npm, pip, twine, dotnet, nuget, swift, maven, gradle"
            exit 1
            ;;
        esac

        # Get CodeArtifact authorization token
        echo "Fetching CodeArtifact authorization token..."
        CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token \
          --domain "${{ inputs.codeartifact_domain }}" \
          --domain-owner "$CA_DOMAIN_OWNER" \
          --region "$CA_REGION" \
          --duration-seconds "$DURATION" \
          --query authorizationToken \
          --output text)"

        # Mask the token in logs
        echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"

        # Export token as environment variable (secure - not exposed as output)
        echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

        # Get repository endpoint URL
        echo "Fetching CodeArtifact repository endpoint..."
        CODEARTIFACT_REPO_URL="$(aws codeartifact get-repository-endpoint \
          --domain "${{ inputs.codeartifact_domain }}" \
          --domain-owner "$CA_DOMAIN_OWNER" \
          --repository "${{ inputs.codeartifact_repository }}" \
          --format "$FORMAT" \
          --region "$CA_REGION" \
          --query repositoryEndpoint \
          --output text)"

        # Export endpoint as environment variable
        echo "CODEARTIFACT_REPO_URL=$CODEARTIFACT_REPO_URL" >> $GITHUB_ENV

        # Set endpoint as output (safe to expose)
        echo "endpoint=$CODEARTIFACT_REPO_URL" >> $GITHUB_OUTPUT

        echo "✅ CodeArtifact token and endpoint configured"
        echo "📦 Domain: ${{ inputs.codeartifact_domain }}"
        echo "📦 Repository: ${{ inputs.codeartifact_repository }}"
        echo "🔧 Tool: ${{ inputs.codeartifact_tool }}"
        if [[ -n "${{ inputs.codeartifact_namespace }}" ]]; then
          echo "🏷️  Namespace: ${{ inputs.codeartifact_namespace }}"
        fi
        echo "🔗 Endpoint: $CODEARTIFACT_REPO_URL"
        echo ""
        echo "💡 Environment variables set:"
        echo "   - CODEARTIFACT_AUTH_TOKEN (masked)"
        echo "   - CODEARTIFACT_REPO_URL"
        echo ""
        echo "📝 Next steps:"
        case "${{ inputs.codeartifact_tool }}" in
          maven)
            echo "   Configure your settings.xml to use \${env.CODEARTIFACT_AUTH_TOKEN}"
            echo "   and \${env.CODEARTIFACT_REPO_URL}"
            ;;
          gradle)
            echo "   Configure your build.gradle to use System.env.CODEARTIFACT_AUTH_TOKEN"
            echo "   and System.env.CODEARTIFACT_REPO_URL"
            ;;
          npm)
            echo "   For Docker builds, pass as build args:"
            echo "   --build-arg CODEARTIFACT_AUTH_TOKEN=\$CODEARTIFACT_AUTH_TOKEN"
            echo "   --build-arg CODEARTIFACT_REPO_URL=\$CODEARTIFACT_REPO_URL"
            ;;
          pip|twine)
            echo "   For Docker builds, pass as build args:"
            echo "   --build-arg CODEARTIFACT_AUTH_TOKEN=\$CODEARTIFACT_AUTH_TOKEN"
            echo "   --build-arg CODEARTIFACT_REPO_URL=\$CODEARTIFACT_REPO_URL"
            ;;
          dotnet|nuget)
            echo "   For Docker builds, pass as build args:"
            echo "   --build-arg CODEARTIFACT_AUTH_TOKEN=\$CODEARTIFACT_AUTH_TOKEN"
            echo "   --build-arg CODEARTIFACT_REPO_URL=\$CODEARTIFACT_REPO_URL"
            ;;
          *)
            echo "   Use environment variables CODEARTIFACT_AUTH_TOKEN and CODEARTIFACT_REPO_URL"
            ;;
        esac
        echo "::endgroup::"

    - name: Log CodeArtifact status
      id: codeartifact-status
      if: inputs.codeartifact_domain != '' && inputs.codeartifact_repository != '' && inputs.codeartifact_tool != ''
      shell: bash
      run: |
        if [[ "${{ inputs.codeartifact_output_token }}" == "true" ]] || [[ "${{ inputs.codeartifact_tool }}" == "maven" ]] || [[ "${{ inputs.codeartifact_tool }}" == "gradle" ]]; then
          echo "::notice::📦 CodeArtifact token configured for ${{ inputs.codeartifact_tool }}"
        else
          echo "::notice::📦 CodeArtifact login successful for ${{ inputs.codeartifact_tool }}"
        fi
        echo "logged_in=true" >> $GITHUB_OUTPUT

    - name: Set CodeArtifact not logged in
      id: codeartifact-status-false
      if: inputs.codeartifact_domain == '' || inputs.codeartifact_repository == '' || inputs.codeartifact_tool == ''
      shell: bash
      run: |
        echo "logged_in=false" >> $GITHUB_OUTPUT

    - name: Summary
      shell: bash
      run: |
        echo "### AWS Login Summary 🔐" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Service | Status | Details |" >> $GITHUB_STEP_SUMMARY
        echo "|---------|--------|---------|" >> $GITHUB_STEP_SUMMARY
        echo "| **AWS** | ✅ Authenticated | Account: ${{ steps.aws.outputs.aws-account-id }} |" >> $GITHUB_STEP_SUMMARY
        echo "| **Region** | 📍 ${{ inputs.aws_region }} | - |" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ inputs.enable_ecr_login }}" == "true" ]]; then
          echo "| **ECR** | ✅ Logged in | Registry: ${{ steps.login-ecr.outputs.registry }} |" >> $GITHUB_STEP_SUMMARY
          if [[ -n "${{ inputs.ecr_repositories }}" ]]; then
            echo "| **ECR Repos** | ✅ Ensured | Repositories: ${{ inputs.ecr_repositories }} |" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        
        if [[ -n "${{ inputs.eks_cluster_name }}" ]]; then
          echo "| **EKS** | ✅ Configured | Cluster: ${{ inputs.eks_cluster_name }} |" >> $GITHUB_STEP_SUMMARY
        fi

        if [[ -n "${{ inputs.codeartifact_domain }}" ]] && [[ -n "${{ inputs.codeartifact_repository }}" ]] && [[ -n "${{ inputs.codeartifact_tool }}" ]]; then
          NAMESPACE_INFO=""
          if [[ -n "${{ inputs.codeartifact_namespace }}" ]]; then
            NAMESPACE_INFO=", Namespace: ${{ inputs.codeartifact_namespace }}"
          fi
          echo "| **CodeArtifact** | ✅ Configured | Domain: ${{ inputs.codeartifact_domain }}, Repo: ${{ inputs.codeartifact_repository }}, Tool: ${{ inputs.codeartifact_tool }}$NAMESPACE_INFO |" >> $GITHUB_STEP_SUMMARY
        fi